"""
report_formatter.py

Formats detected edit-war incidents into WikiText suitable
for posting on Wikipedia admin noticeboards (e.g., WP:AN3).

No API calls.
No DB access.
Pure formatting logic.
"""

from typing import List, Dict
from datetime import datetime
from src.utils.logger import get_logger

logger = get_logger("report_formatter")


def _format_timestamp(ts: datetime) -> str:
    """Format timestamp for WikiText."""
    return ts.strftime("%Y-%m-%d %H:%M:%S (UTC)")


def format_three_rr_reports(cases: List[Dict]) -> str:
    """
    Format 3RR violation cases into WikiText.

    Args:
        cases (List[Dict]): Output from detect_three_rr()

    Returns:
        str: WikiText report
    """

    if not cases:
        return "== Three-Revert Rule violations ==\n\nNo potential 3RR violations detected.\n"

    lines = ["== Three-Revert Rule violations ==\n"]

    for c in cases:
        lines.append(
            f"* '''Article''': [[{c['article']}]]\n"
            f"  * '''User''': [[User:{c['user']}]]\n"
            f"  * '''Reverts (24h)''': {c['revert_count']}\n"
            f"  * '''Last revert''': {_format_timestamp(c['last_revert_time'])}\n"
        )

    logger.info("Formatted %d 3RR cases", len(cases))
    return "\n".join(lines)


def format_mutual_revert_reports(cases: List[Dict]) -> str:
    """
    Format mutual revert (edit war) cases into WikiText.

    Args:
        cases (List[Dict]): Output from detect_mutual_reverts()

    Returns:
        str: WikiText report
    """

    if not cases:
        return "== Mutual revert edit wars ==\n\nNo mutual revert edit wars detected.\n"

    lines = ["== Mutual revert edit wars ==\n"]

    for c in cases:
        lines.append(
            f"* '''Article''': [[{c['article']}]]\n"
            f"  * '''User A''': [[User:{c['user_a']}]] "
            f"({c['reverts_user_a']} reverts)\n"
            f"  * '''User B''': [[User:{c['user_b']}]] "
            f"({c['reverts_user_b']} reverts)\n"
            f"  * '''Last interaction''': {_format_timestamp(c['last_interaction'])}\n"
        )

    logger.info("Formatted %d mutual revert cases", len(cases))
    return "\n".join(lines)


def format_full_report(
    three_rr_cases: List[Dict],
    mutual_cases: List[Dict]
) -> str:
    """
    Combine all detected cases into a single WikiText report.

    Returns:
        str: Complete WikiText report
    """

    header = (
        "This is an automated report generated by '''EditWarCatcherBot'''.\n"
        "The report highlights possible edit-warring behavior for human review.\n"
        "Please verify before taking administrative action.\n\n"
    )

    report = (
        header +
        format_three_rr_reports(three_rr_cases) +
        "\n\n" +
        format_mutual_revert_reports(mutual_cases)
    )

    logger.info("Formatted full report")
    return report
